/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VendedoresRouteImport } from './routes/vendedores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresRoute = VendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/tienda': typeof TiendaRoute
  '/usuarios': typeof UsuariosRoute
  '/vendedores': typeof VendedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/tienda': typeof TiendaRoute
  '/usuarios': typeof UsuariosRoute
  '/vendedores': typeof VendedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/tienda': typeof TiendaRoute
  '/usuarios': typeof UsuariosRoute
  '/vendedores': typeof VendedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historia' | '/tienda' | '/usuarios' | '/vendedores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historia' | '/tienda' | '/usuarios' | '/vendedores'
  id: '__root__' | '/' | '/historia' | '/tienda' | '/usuarios' | '/vendedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriaRoute: typeof HistoriaRoute
  TiendaRoute: typeof TiendaRoute
  UsuariosRoute: typeof UsuariosRoute
  VendedoresRoute: typeof VendedoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores': {
      id: '/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof VendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriaRoute: HistoriaRoute,
  TiendaRoute: TiendaRoute,
  UsuariosRoute: UsuariosRoute,
  VendedoresRoute: VendedoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
